import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";

import type { ReactNode } from "react";

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

import "@hackyard/ui/globals.css";

import { ProviderTree } from "@/providers";

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html
      className={`${jakartaSans.variable} antialiased`}
      lang="en"
      suppressHydrationWarning={true}
    >
      <body>
        <ProviderTree>{children}</ProviderTree>
      </body>
    </html>
  );
};

export default RootLayout;
